In [1]:
import pandas as pd  

In [22]:
#Sorting
csvData = pd.read_csv("C:/Users/SAKSHI MARATHE/Downloads/records.csv")        

In [23]:
print("\nBefore sorting:") 


Before sorting:


In [24]:
print(csvData) 

   ID    Name    Role  Salary
0   1  Pankaj  Editor   10000
1   2    Lisa  Editor    8000
2   3   David  Author    6000
3   4     Ram  Author    4000
4   5  Anupam  Author    5000


In [25]:
csvData.sort_values(["Salary"], axis=0, ascending=[False], inplace=True) 

In [26]:
csvData.sort_values(["Salary"], axis=0, ascending=[True], inplace=True) 

In [27]:
print("\nAfter sorting:") 


After sorting:


In [28]:
print(csvData) 

   ID    Name    Role  Salary
3   4     Ram  Author    4000
4   5  Anupam  Author    5000
2   3   David  Author    6000
1   2    Lisa  Editor    8000
0   1  Pankaj  Editor   10000


In [33]:
#transpose
df = pd.read_csv("C:/Users/SAKSHI MARATHE/Downloads/records.csv") 

In [34]:
print(df) 

   ID    Name    Role  Salary
0   1  Pankaj  Editor   10000
1   2    Lisa  Editor    8000
2   3   David  Author    6000
3   4     Ram  Author    4000
4   5  Anupam  Author    5000


In [35]:
print(df.T) 

             0       1       2       3       4
ID           1       2       3       4       5
Name    Pankaj    Lisa   David     Ram  Anupam
Role    Editor  Editor  Author  Author  Author
Salary   10000    8000    6000    4000    5000


In [36]:
print(df.shape)

(5, 4)


In [37]:
print(df.size) 

20


In [40]:
#Shape
df = pd.read_csv("C:/Users/SAKSHI MARATHE/Downloads/records.csv") 

In [41]:
print(df.shape) 

(5, 4)


In [42]:
print(df.size) 

20


In [43]:
#reshape
import numpy as np

In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [45]:
newarr = arr.reshape(4, 3)

In [46]:
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
